### ISSUE TITLE
Qubino ZMNHADx create phantom/fake sensors humidity and CO2 sensors

### ISSUE THREAD

**Issue by bjacobse** [OpenZWave/open-zwave#1658] opened 2018-11-29 20:46 UTC
In my domoticz ver Version: 4.9700,  3 pcs of  Qubino ZMNHADx Flush 1 Relay that all have DS18B20 temperature sensor suddenly seems to have have created extra sensors, so it contained a humidity and CO2 sensors, so then Domoticz created a combined sensor instead of only have the temperature sensor. I got some help from Domoticz forum and understand the issue is an OpenZwave issue.
The proposed manual edit is to remove those sensors created below COMMAND_CLASS_SENSOR_MULTILEVEL, but I don't know yet if this will "cure" the issue or not

I have the link to Domoticz forum where this have been discussed.
https://www.domoticz.com/forum/viewtopic.php?f=24&t=19280#p198890

**Comment by Fishwaldo** [comment] 2018-11-29 23:59
Please shutdown the app, remove zwcfg_*.xml and restart with logging enabled and post the OZW log file.

**Comment by bjacobse** [comment] 2018-12-01 17:16
It seems after removing zwcfg_*.xml file my Qubino devices is not being activated properly, I am not able to get temperature readings, and some configuration  seems to be missing for them too.
[OZW_Log.txt](https://github.com/OpenZWave/open-zwave/files/2636084/OZW_Log.txt)

**Comment by nechry** [comment] 2018-12-02 15:11
I also have from time to time phantom/fake sensors reported to my devices.

**Comment by nicweb84** [comment] 2019-01-23 13:16
Same thing for me with a Qubino ZMNHIDX. It suddenly report a fake humidity sensor

**Comment by bjacobse** [comment] 2019-01-23 20:46
Hi Niceweb84
I can recommend to backup youtr cfg.xml file
Stop your homeautomation system
Then then edit cfg.xml file, find your device that suddenly have this fake humidity sensor and remote the whole line.
then restart home automation system and check if your fake sensor is gone

**Comment by Fishwaldo** [comment] 2019-01-25 03:21
Duplicate of #1687

**Closed by Fishwaldo** 2019-01-25 03:21 UTC
Labels: Investigate
