### ISSUE TITLE
Devolo door / window sensor 2648 (D-Link derivate)

### ISSUE THREAD

**Issue by liber-8** [OpenZWave/open-zwave#846] opened 2016-04-13 15:39 UTC
Hi devs,

as with #738 / #752 there's also a door / window sensor from Devolo (http://products.z-wavealliance.org/products/1130) which is rebranded and the same device as DCH-Z110 from D-Link (http://products.z-wavealliance.org/products/1151).

It would be great if you could add it to the manufacturer_specific.xml.

Thanks

**Comment by Fishwaldo** [comment] 2016-04-25 05:02
Could you please post the Type and ID of this device (and which one its a duplicate of) as its not specified in the product manuals.

**Comment by liber-8** [comment] 2016-04-25 11:25
Sure..

This is the entry in manufacturer_specific.xml for the D-Link device:

`<Product type="0002" id="000e" name="DCH-Z110 Door/Window 3 in 1 sensor" config="dlink/dch-z110.xml"/>`

And this is what I see in my logs for the Devolo clone:

```
sensor.unknown_id0175_unknown_type0002_id000e_temperature_2
sensor.unknown_id0175_unknown_type0002_id000e_luminance_2
sensor.unknown_id0175_unknown_type0002_id000e_alarm_level_2
sensor.unknown_id0175_unknown_type0002_id000e_alarm_type_2
binary_sensor.unknown_id0175_unknown_type0002_id000e_sensor_2
sensor.unknown_id0175_unknown_type0002_id000e_access_control_2
sensor.unknown_id0175_unknown_type0002_id000e_sourcenodeid_2
```

Just out of curiosity.. could I insert

`<Product type="0002" id="0175" name="Devolo Door/Window 3 in 1 sensor" config="dlink/dch-z110.xml"/>`

below the D-Link entry to get the Devolo device added / supported or is there some other magic that needs to be done?

Thanks.

**Comment by nechry** [comment] 2016-04-25 11:39
we also need the Develo Manufacturer id. give use the xml element for this node from your zwcfgxxx.xml file

**Comment by liber-8** [comment] 2016-04-25 13:03
```
                <Manufacturer id="175" name="Unknown: id=0175">
                        <Product type="2" id="e" name="Unknown: type=0002, id=000e" />
                </Manufacturer>
```

**Comment by nechry** [comment] 2016-04-25 13:47
ok so I will add this:
```<Manufacturer id="175" name="Devolo">
		<Product type="0002" id="000e" name="DCH-Z110 Door/Window 3 in 1 sensor" config="dlink/dch-z110.xml"/>
    </Manufacturer>```

**Comment by nechry** [comment] 2016-04-25 13:56
I prepare this :
https://github.com/jeedom/plugin-openzwave/commit/693485a6ec8689e8cd2cc481b1875af6e65e6514
we merge this week

**Comment by liber-8** [comment] 2016-04-25 14:11
cool, thanks :-)

**Comment by liber-8** [comment] 2016-04-25 15:09
So maybe it makes sense to move line 205

`<Product type="0005" id="0175" name="Devolo Home Control Radiator Thermostat" config="danfoss/z.xml"/>`

into the Devolo manufacturer element too.

**Comment by nechry** [comment] 2016-04-25 18:26
we have to be sure (proove) this device is related to Manufacturer id 175. do you also have this device?

**Comment by liber-8** [comment] 2016-04-25 18:40
Yes I do.. right now it shows up as:

```
<Manufacturer id="2" name="Danfoss">
  <Product type="5" id="175" name="Devolo Home Control Radiator Thermostat" />
</Manufacturer>
```

But I guess it's because it already has an entry in manufacturer_specific.xml, right?

I can delete that entry, reset my configuration and rescan tomorrow if that helps.

**Comment by nechry** [comment] 2016-04-25 18:49
No, is relative to Manufacturer id="2" name="Danfoss". Theres informations (ids) come from device it self.
Some devices are rebranded with old Manufacturer id

**Comment by nechry** [comment] 2016-06-08 08:41
the jeedom config
https://github.com/OpenZWave/open-zwave/pull/901
are now merge

**Closed by nechry** 2016-06-08 08:41 UTC
Labels: ConfigUpdate, NotReady
