### ISSUE TITLE
After a binary switch is dead, we can not recover it

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OpenZWave/open-zwave#190] opened 2015-03-14 09:55 UTC
```
What steps will reproduce the problem?
1.Add a binary switch and control it. It's OK.
2.Remove the power of the switch and wait for a couple of mninutes until it is 
declared as dead.
3. Put the power of binary switch back. We can not control it any more. All 
commands are dropped.

I try to send node info from the b8inary switch. The OZW receive it. However, 
it does nothing to bring it out of the dead state. 
```

Original issue reported on code.google.com by `wyc...@gmail.com` on 14 Mar 2013 at 9:22

Attachments:
- [OZW_Log.txt](https://storage.googleapis.com/google-code-attachments/open-zwave/issue-190/comment-0/OZW_Log.txt)
- [zwcfg_0x01621234.xml](https://storage.googleapis.com/google-code-attachments/open-zwave/issue-190/comment-0/zwcfg_0x01621234.xml)

**Comment by rwa** [comment] 2017-03-30 04:57
I am having similar problems with a Linear WD500Z-1.  Intermittently, I get the following in the log:

Info, Node003, WARNING: ZW_SEND_DATA failed. No ACK received - device may be asleep.
Warning, Node003, WARNING: Device is not a sleeping node.

It appears that if this occurs 3 times, the next lines are:

Error, Node003, ERROR: node presumed dead

All commands to the node are then dropped with messages like:

Error, Node003, ERROR: Dropping command because node is presumed dead

I notice from the discussion immediately above that the RTT for this node is indeed variable:

grep Node003 OZW_Log.txt | grep RTT produces:

2017-03-29 08:00:01.034 Info, Node003, Request RTT 97 Average Request RTT 418
2017-03-29 08:00:02.678 Info, Node003, Request RTT 1644 Average Request RTT 1031
2017-03-29 08:00:06.200 Info, Node003, Response RTT 5165 Average Response RTT 2694
2017-03-29 08:00:18.140 Info, Node003, Request RTT 1884 Average Request RTT 1457
2017-03-29 08:00:20.681 Info, Node003, Response RTT 4425 Average Response RTT 3559
2017-03-29 08:00:21.035 Info, Node003, Response RTT 353 Average Response RTT 1956
2017-03-29 08:00:25.359 Info, Node003, Response RTT 4677 Average Response RTT 3316
2017-03-29 21:00:01.552 Info, Node003, Request RTT 615 Average Request RTT 1036
2017-03-29 21:00:02.129 Info, Node003, Request RTT 577 Average Request RTT 806
2017-03-29 21:00:05.925 Info, Node003, Response RTT 4372 Average Response RTT 3844
2017-03-29 21:00:31.112 Info, Node003, Request RTT 157 Average Request RTT 481
2017-03-29 21:00:31.662 Info, Node003, Request RTT 550 Average Request RTT 515
2017-03-29 21:00:35.743 Info, Node003, Response RTT 4630 Average Response RTT 4237
2017-03-29 21:01:01.048 Info, Node003, Request RTT 63 Average Request RTT 289
2017-03-29 21:01:01.443 Info, Node003, Request RTT 395 Average Request RTT 342
2017-03-29 21:01:31.072 Info, Node003, Request RTT 63 Average Request RTT 202
2017-03-29 21:01:31.135 Info, Node003, Request RTT 62 Average Request RTT 132
2017-03-29 21:01:31.174 Info, Node003, Response RTT 101 Average Response RTT 2169
2017-03-29 21:02:01.101 Info, Node003, Request RTT 63 Average Request RTT 97
2017-03-29 21:02:02.428 Info, Node003, Request RTT 1326 Average Request RTT 711
2017-03-29 21:02:05.518 Info, Node003, Response RTT 4416 Average Response RTT 3292
2017-03-29 21:02:31.129 Info, Node003, Request RTT 63 Average Request RTT 387

From the neighbor matrix, it seems there should be 3 2-hop paths to this node, and about a dozen 3-hop paths.  I would expect this is sufficient for reliable communication, but clearly something is amiss here.

Any help in further clarifying this problem appreciated.

**Comment by dcarrion87** [comment] 2017-10-20 08:51
Same way to reproduce as the original post. I have to re-add to network every time.

       <Node id="15" name="Lounge Dual" location="" basic="4" generic="16" specific="1" type="Binary Power Switch" listening="true" frequentListening="false" beaming="true" routing="true" max_baud_rate="40000" version="4" query_stage="P
                <Manufacturer id="97" name="Schlage Link">
                        <Product type="1122" id="5501" name="Unknown: type=1122, id=5501" />

Lucky I don't get power outages that often but have been doing a bit of work around the house and pain having to re-add this one binary switch every time.

**Comment by janakelarsson** [comment] 2018-06-25 13:39
I seem to have this problem, still. Any news on this? I have nine nodes at small distance, three of which now are dead. And die again a while after having manually revived them.

I understand it is undesirable to send data to dead nodes, possibly delaying timely access of other nodes. But would it be possible to automatically send a NOP to "test" the dead nodes, say once each 24-hour period?

**Comment by janakelarsson** [comment] 2018-07-01 20:44
The three failing devices are Philio Technology Corporation PAN11-4 Smart Energy Plug In Switch.

I just compiled Domoticz against OpenZwave 1.4-3091 and restarted.

Seems to work now, but that may be the restart, I will need to let that run for some time to know for sure it helped.

**Comment by janakelarsson** [comment] 2019-03-25 06:33
After having almost all switches die one after another I decided to try something new. So I stopped domoticz and started the z-way server. Performing a "Force interview" in the Expert interface (Configuration->Interview) seems to revive the switches. If only z-way had a daylight timer, I'd keep that. Switching back to domoticz for now.

**Comment by Fishwaldo** [comment] 2019-05-13 06:35
Have you tried Manager::HasNodeFailed ?

http://www.openzwave.com/dev/classOpenZWave_1_1Manager.html#a8000a9c5faf089be93daa63e92573fd5

closing this as its duplicate with #808

**Closed by Fishwaldo** 2019-05-13 06:35 UTC
